#!/usr/bin/env bash
#Bash script that displays Best School 10 time

i=0
while [ $i -le 9 ]
do
        if [ $i -eq 3 ]
        then
                echo "bad luck"
        elif [ $i -eq 7 ]
        then
                echo "good luck"
        else
                echo "Best School"
        fi
        ((i++))
done
